// <auto-generated />
using System;
using JuniorTemplate.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuniorTemplate.Data.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20220628104108_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("JuniorTemplate.Data.Entities.Tea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e48cebea-f7e7-4e67-8e8c-9e434e2662ed"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9168),
                            Name = "Earl Gray",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("35eebc22-1d9c-4381-97ee-dbeee1bb0f7d"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9833),
                            Name = "Rose Tea",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("8389a749-f167-4521-8d33-a7330d72629f"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9835),
                            Name = "English Breakfast Tea",
                            Price = 18m
                        },
                        new
                        {
                            Id = new Guid("c68b898d-8357-4c72-a53b-80dbd940dcea"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9837),
                            Name = "Big Sur Tea",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("20da3a9c-b034-405d-8c63-c8e9aad46a64"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9838),
                            Name = "Big Sur Tea",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("b983e730-ace9-42b8-9cec-959e0804551a"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9839),
                            Name = "Jasmine Pearls",
                            Price = 41m
                        },
                        new
                        {
                            Id = new Guid("8aae270e-1dfc-40d9-b117-a895a3e84931"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9840),
                            Name = "Dragonwell",
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("ff3169d8-10f9-4908-b7a4-70cce6a70568"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9850),
                            Name = "White Peach Tea",
                            Price = 29m
                        },
                        new
                        {
                            Id = new Guid("f2fcdcdb-132a-463a-becd-315e2116bed2"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9851),
                            Name = "Vanilla Berry Tea",
                            Price = 21m
                        },
                        new
                        {
                            Id = new Guid("349ffc08-d6e0-412a-8bec-f0e977f9a84c"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9853),
                            Name = "Chaga Chai Mushroom Tea",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("ed10c4da-466c-4339-9e44-c05bf651d613"),
                            Created = new DateTime(2022, 6, 28, 10, 41, 7, 609, DateTimeKind.Utc).AddTicks(9854),
                            Name = "Naked Pu-erh Tea",
                            Price = 27m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
